# Generated by Django 2.1.7 on 2019-03-15 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

  initial = True

  dependencies = []

  operations = [
      migrations.CreateModel(
          name='ApiKey',
          fields=[
              ('id',
               models.AutoField(
                   auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
              ('subscriber_name',
               models.CharField(db_index=True, max_length=255, verbose_name='subscriber name')),
              ('api_key', models.CharField(max_length=255, verbose_name='API key')),
          ],
      ),
  ]
