# Generated by Django 2.2.4 on 2019-10-02 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_token', models.CharField(db_index=True, max_length=31, verbose_name='series token')),
                ('random_state', models.BigIntegerField(verbose_name='current state')),
                ('card_count', models.PositiveIntegerField(verbose_name='current state')),
                ('is_closed', models.BooleanField(blank=True, default=False, verbose_name='is closed')),
            ],
        ),
        migrations.CreateModel(
            name='BoxDefinition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=63, verbose_name='name')),
                ('details', models.CharField(blank=True, max_length=255, null=True, verbose_name='details')),
                ('log2size', models.PositiveIntegerField(default=22, verbose_name='log2(size)')),
                ('amount_in', models.PositiveIntegerField(default=1, verbose_name='amount in')),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=63, unique=True, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='Outcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=63, verbose_name='name')),
                ('details', models.CharField(blank=True, max_length=255, null=True, verbose_name='details')),
                ('probability', models.PositiveIntegerField(default=1, verbose_name='probability')),
                ('amount_out', models.PositiveIntegerField(default=0, verbose_name='amount out')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
                ('box_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_outcomes', to='api.BoxDefinition')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(db_index=True, verbose_name='sequence')),
                ('user_token', models.CharField(db_index=True, max_length=31, verbose_name='user token')),
                ('consumed', models.BooleanField(db_index=True, default=False, verbose_name='consumed')),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='api.Box')),
                ('outcome', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Outcome')),
            ],
        ),
        migrations.CreateModel(
            name='BoxProspectus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_random_state', models.BigIntegerField(verbose_name='initial state')),
                ('actual_hit_rate', models.FloatField(verbose_name='actual hit rate')),
                ('actual_return', models.IntegerField(verbose_name='actual return')),
                ('max_amount_out', models.IntegerField(verbose_name='max amount out')),
                ('box_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='box_prospectus', to='api.BoxDefinition')),
            ],
        ),
        migrations.AddField(
            model_name='boxdefinition',
            name='subscribers',
            field=models.ManyToManyField(related_name='box_definitions', to='api.Subscriber'),
        ),
        migrations.AddField(
            model_name='box',
            name='box_prospectus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boxes', to='api.BoxProspectus'),
        ),
        migrations.AddField(
            model_name='box',
            name='subscriber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boxes', to='api.Subscriber'),
        ),
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(max_length=63, unique=True, verbose_name='API key')),
                ('deactivated', models.BooleanField(default=False, verbose_name='deactivated')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='api.Subscriber')),
            ],
        ),
    ]
