# Generated by Django 2.2.2 on 2019-08-18 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoxDefinition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=63, verbose_name='title')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='description')),
                ('log2size', models.PositiveIntegerField(default=22, verbose_name='log2(size)')),
                ('amount_in', models.PositiveIntegerField(default=1, verbose_name='amount in')),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=63, unique=True, verbose_name='name')),
            ],
        ),
        migrations.RemoveField(
            model_name='apikey',
            name='subscriber_name',
        ),
        migrations.AddField(
            model_name='apikey',
            name='deactivated',
            field=models.BooleanField(default=False, verbose_name='deactivated'),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='api_key',
            field=models.CharField(max_length=63, unique=True, verbose_name='API key'),
        ),
        migrations.CreateModel(
            name='Outcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=63, verbose_name='title')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='description')),
                ('probability', models.PositiveIntegerField(default=1, verbose_name='probability')),
                ('amount_out', models.PositiveIntegerField(default=0, verbose_name='amount out')),
                ('box_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcomes', to='api.BoxDefinition')),
            ],
        ),
        migrations.AddField(
            model_name='boxdefinition',
            name='subscriber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='box_definitions', to='api.Subscriber'),
        ),
        migrations.AddField(
            model_name='apikey',
            name='subscriber',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='api.Subscriber'),
            preserve_default=False,
        ),
    ]
