# Generated by Django 2.2.4 on 2019-10-12 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20191009_2111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='box',
            name='random_state',
        ),
        migrations.RemoveField(
            model_name='boxprospectus',
            name='initial_random_state',
        ),
        migrations.AddField(
            model_name='box',
            name='random_state_0',
            field=models.IntegerField(blank=True, default=0, verbose_name='rng state 0'),
        ),
        migrations.AddField(
            model_name='box',
            name='random_state_1',
            field=models.IntegerField(blank=True, default=0, verbose_name='rng state 1'),
        ),
        migrations.AddField(
            model_name='box',
            name='random_state_2',
            field=models.IntegerField(blank=True, default=0, verbose_name='rng state 2'),
        ),
        migrations.AddField(
            model_name='box',
            name='random_state_3',
            field=models.IntegerField(blank=True, default=0, verbose_name='rng state 3'),
        ),
        migrations.AddField(
            model_name='boxprospectus',
            name='initial_random_seed',
            field=models.BigIntegerField(default=0, verbose_name='initial random seed'),
        ),
    ]
