# Generated by Django 2.2.4 on 2019-08-25 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190821_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outcome',
            name='box_definition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_outcomes', to='api.BoxDefinition'),
        ),
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_seed', models.BigIntegerField(verbose_name='probability')),
                ('actual_hit_rate', models.FloatField(verbose_name='actual hit rate')),
                ('actual_return', models.IntegerField(verbose_name='actual return')),
                ('max_amount_out', models.IntegerField(verbose_name='actual return')),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boxes', to='api.BoxDefinition')),
            ],
        ),
    ]
