# Generated by Django 2.2.4 on 2019-08-29 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190825_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='max_amount_out',
            field=models.IntegerField(verbose_name='max amount out'),
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(db_index=True, verbose_name='sequence')),
                ('user_token', models.BooleanField(db_index=True, default=False, verbose_name='consumed')),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='api.Box')),
                ('outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Outcome')),
            ],
        ),
    ]
