# Generated by Django 2.2.4 on 2019-08-29 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190829_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='outcome',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='order'),
        ),
    ]
