# Generated by Django 2.2.4 on 2019-08-30 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_outcome_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='consumed',
            field=models.BooleanField(db_index=True, default=False, verbose_name='consumed'),
        ),
        migrations.AlterField(
            model_name='card',
            name='user_token',
            field=models.CharField(blank=True, db_index=True, max_length=31, null=True, verbose_name='user token'),
        ),
    ]
