# Generated by Django 2.2.4 on 2019-08-30 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20190830_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='outcome',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Outcome'),
        ),
    ]
